// +build go1.9

// Copyright 2017 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder

package cdn

import original "github.com/Azure/azure-sdk-for-go/service/cdn/management/2015-06-01/cdn"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type ManagementClient = original.ManagementClient
type EndpointsClient = original.EndpointsClient
type CustomDomainsClient = original.CustomDomainsClient
type OriginsClient = original.OriginsClient
type OperationsClient = original.OperationsClient
type ProfilesClient = original.ProfilesClient
type CustomDomainResourceState = original.CustomDomainResourceState

const (
	Active		CustomDomainResourceState	= original.Active
	Creating	CustomDomainResourceState	= original.Creating
	Deleting	CustomDomainResourceState	= original.Deleting
)

type EndpointResourceState = original.EndpointResourceState

const (
	EndpointResourceStateCreating	EndpointResourceState	= original.EndpointResourceStateCreating
	EndpointResourceStateDeleting	EndpointResourceState	= original.EndpointResourceStateDeleting
	EndpointResourceStateRunning	EndpointResourceState	= original.EndpointResourceStateRunning
	EndpointResourceStateStarting	EndpointResourceState	= original.EndpointResourceStateStarting
	EndpointResourceStateStopped	EndpointResourceState	= original.EndpointResourceStateStopped
	EndpointResourceStateStopping	EndpointResourceState	= original.EndpointResourceStateStopping
)

type OriginResourceState = original.OriginResourceState

const (
	OriginResourceStateActive	OriginResourceState	= original.OriginResourceStateActive
	OriginResourceStateCreating	OriginResourceState	= original.OriginResourceStateCreating
	OriginResourceStateDeleting	OriginResourceState	= original.OriginResourceStateDeleting
)

type ProfileResourceState = original.ProfileResourceState

const (
	ProfileResourceStateActive	ProfileResourceState	= original.ProfileResourceStateActive
	ProfileResourceStateCreating	ProfileResourceState	= original.ProfileResourceStateCreating
	ProfileResourceStateDeleting	ProfileResourceState	= original.ProfileResourceStateDeleting
	ProfileResourceStateDisabled	ProfileResourceState	= original.ProfileResourceStateDisabled
)

type ProvisioningState = original.ProvisioningState

const (
	ProvisioningStateCreating	ProvisioningState	= original.ProvisioningStateCreating
	ProvisioningStateFailed		ProvisioningState	= original.ProvisioningStateFailed
	ProvisioningStateSucceeded	ProvisioningState	= original.ProvisioningStateSucceeded
)

type QueryStringCachingBehavior = original.QueryStringCachingBehavior

const (
	BypassCaching		QueryStringCachingBehavior	= original.BypassCaching
	IgnoreQueryString	QueryStringCachingBehavior	= original.IgnoreQueryString
	NotSet			QueryStringCachingBehavior	= original.NotSet
	UseQueryString		QueryStringCachingBehavior	= original.UseQueryString
)

type ResourceType = original.ResourceType

const (
	MicrosoftCdnProfilesEndpoints ResourceType = original.MicrosoftCdnProfilesEndpoints
)

type SkuName = original.SkuName

const (
	Premium		SkuName	= original.Premium
	Standard	SkuName	= original.Standard
)

type CheckNameAvailabilityInput = original.CheckNameAvailabilityInput
type CheckNameAvailabilityOutput = original.CheckNameAvailabilityOutput
type CustomDomain = original.CustomDomain
type CustomDomainListResult = original.CustomDomainListResult
type CustomDomainParameters = original.CustomDomainParameters
type CustomDomainProperties = original.CustomDomainProperties
type CustomDomainPropertiesParameters = original.CustomDomainPropertiesParameters
type DeepCreatedOrigin = original.DeepCreatedOrigin
type DeepCreatedOriginProperties = original.DeepCreatedOriginProperties
type Endpoint = original.Endpoint
type EndpointCreateParameters = original.EndpointCreateParameters
type EndpointListResult = original.EndpointListResult
type EndpointProperties = original.EndpointProperties
type EndpointPropertiesCreateParameters = original.EndpointPropertiesCreateParameters
type EndpointPropertiesUpdateParameters = original.EndpointPropertiesUpdateParameters
type EndpointUpdateParameters = original.EndpointUpdateParameters
type ErrorResponse = original.ErrorResponse
type LoadParameters = original.LoadParameters
type Operation = original.Operation
type OperationDisplay = original.OperationDisplay
type OperationListResult = original.OperationListResult
type Origin = original.Origin
type OriginListResult = original.OriginListResult
type OriginParameters = original.OriginParameters
type OriginProperties = original.OriginProperties
type OriginPropertiesParameters = original.OriginPropertiesParameters
type Profile = original.Profile
type ProfileCreateParameters = original.ProfileCreateParameters
type ProfileListResult = original.ProfileListResult
type ProfileProperties = original.ProfileProperties
type ProfilePropertiesCreateParameters = original.ProfilePropertiesCreateParameters
type ProfileUpdateParameters = original.ProfileUpdateParameters
type PurgeParameters = original.PurgeParameters
type Resource = original.Resource
type Sku = original.Sku
type SsoURI = original.SsoURI
type TrackedResource = original.TrackedResource
type ValidateCustomDomainInput = original.ValidateCustomDomainInput
type ValidateCustomDomainOutput = original.ValidateCustomDomainOutput
type NameAvailabilityClient = original.NameAvailabilityClient

func NewNameAvailabilityClient(subscriptionID string) NameAvailabilityClient {
	return original.NewNameAvailabilityClient(subscriptionID)
}
func NewNameAvailabilityClientWithBaseURI(baseURI string, subscriptionID string) NameAvailabilityClient {
	return original.NewNameAvailabilityClientWithBaseURI(baseURI, subscriptionID)
}
func NewCustomDomainsClient(subscriptionID string) CustomDomainsClient {
	return original.NewCustomDomainsClient(subscriptionID)
}
func NewCustomDomainsClientWithBaseURI(baseURI string, subscriptionID string) CustomDomainsClient {
	return original.NewCustomDomainsClientWithBaseURI(baseURI, subscriptionID)
}
func NewOriginsClient(subscriptionID string) OriginsClient {
	return original.NewOriginsClient(subscriptionID)
}
func NewOriginsClientWithBaseURI(baseURI string, subscriptionID string) OriginsClient {
	return original.NewOriginsClientWithBaseURI(baseURI, subscriptionID)
}
func NewOperationsClient(subscriptionID string) OperationsClient {
	return original.NewOperationsClient(subscriptionID)
}
func NewOperationsClientWithBaseURI(baseURI string, subscriptionID string) OperationsClient {
	return original.NewOperationsClientWithBaseURI(baseURI, subscriptionID)
}
func NewProfilesClient(subscriptionID string) ProfilesClient {
	return original.NewProfilesClient(subscriptionID)
}
func NewProfilesClientWithBaseURI(baseURI string, subscriptionID string) ProfilesClient {
	return original.NewProfilesClientWithBaseURI(baseURI, subscriptionID)
}
func New(subscriptionID string) ManagementClient {
	return original.New(subscriptionID)
}
func NewWithBaseURI(baseURI string, subscriptionID string) ManagementClient {
	return original.NewWithBaseURI(baseURI, subscriptionID)
}
func UserAgent() string {
	return original.UserAgent()
}
func Version() string {
	return original.Version()
}
func NewEndpointsClient(subscriptionID string) EndpointsClient {
	return original.NewEndpointsClient(subscriptionID)
}
func NewEndpointsClientWithBaseURI(baseURI string, subscriptionID string) EndpointsClient {
	return original.NewEndpointsClientWithBaseURI(baseURI, subscriptionID)
}
