// +build go1.9

// Copyright 2017 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder

package redis

import original "github.com/Azure/azure-sdk-for-go/service/redis/management/2015-08-01/redis"

type GroupClient = original.GroupClient

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type ManagementClient = original.ManagementClient
type KeyType = original.KeyType

const (
	Primary		KeyType	= original.Primary
	Secondary	KeyType	= original.Secondary
)

type RebootType = original.RebootType

const (
	AllNodes	RebootType	= original.AllNodes
	PrimaryNode	RebootType	= original.PrimaryNode
	SecondaryNode	RebootType	= original.SecondaryNode
)

type SkuFamily = original.SkuFamily

const (
	C	SkuFamily	= original.C
	P	SkuFamily	= original.P
)

type SkuName = original.SkuName

const (
	Basic		SkuName	= original.Basic
	Premium		SkuName	= original.Premium
	Standard	SkuName	= original.Standard
)

type AccessKeys = original.AccessKeys
type CreateOrUpdateParameters = original.CreateOrUpdateParameters
type ListKeysResult = original.ListKeysResult
type ListResult = original.ListResult
type Properties = original.Properties
type ReadableProperties = original.ReadableProperties
type ReadablePropertiesWithAccessKey = original.ReadablePropertiesWithAccessKey
type RebootParameters = original.RebootParameters
type RegenerateKeyParameters = original.RegenerateKeyParameters
type Resource = original.Resource
type ResourceType = original.ResourceType
type ResourceWithAccessKey = original.ResourceWithAccessKey
type Sku = original.Sku

func New(subscriptionID string) ManagementClient {
	return original.New(subscriptionID)
}
func NewWithBaseURI(baseURI string, subscriptionID string) ManagementClient {
	return original.NewWithBaseURI(baseURI, subscriptionID)
}
func UserAgent() string {
	return original.UserAgent()
}
func Version() string {
	return original.Version()
}
func NewGroupClient(subscriptionID string) GroupClient {
	return original.NewGroupClient(subscriptionID)
}
func NewGroupClientWithBaseURI(baseURI string, subscriptionID string) GroupClient {
	return original.NewGroupClientWithBaseURI(baseURI, subscriptionID)
}
